[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'gtags.vim'

[[plugins]]
repo = 'tComment'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'smartchr'

[[plugins]]
repo = 'a.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'justmao945/vim-clang'
filetypes = ['c', 'cpp']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
